site_name: Timelion Google API plugin
site_url: https://github.com/bahaaldine/timelion-google-api
site_description: Timelion Google API plugin
site_author: bahaaldine

theme: readthedocs

repo_url: https://github.com/bahaaldine/timelion-google-api

pages:
- Home: index.md
- Installation: installation.md
- Functions list:
  - functions/ganalytics.md
  
copyright: Elastic
  

  
